language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo sed -i "s/precise/trusty/g" /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get -qq --no-install-recommends install gcc-4.8 cmake pkg-config doxygen libgtk-3-dev libexpat1-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - # DEBUG:
  - pwd
  - gcc --version
  - clang --version
  - cmake --version
  - pkg-config --version
  - doxygen --version

install:
  - mkdir build
  - cd build
  - cmake ../ -DMAIN=1

script:
  - make -j 8
  - sudo make install
  - # TEST:
  - /usr/local/bin/info /home/travis/build/prozum/midiogre/res/test.mid
  - /usr/local/bin/extract /home/travis/build/prozum/midiogre/res/test.mid

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "1fIoq5UgyTMR/3PurWRdzKLdO3Zbc6BWZ9sfWmtnM/GVzdqi5AhUkvw5QSBJ+482FtV2ib9G6a9lutyCgnbxOZiCcgDALLm9BigK8t/fb6x9R9cT0Nw6yGmSh5pUYpkK9pwvPq/eERlGCXy9SE2qCV3/B+W/rrE2fJzA5kRe4BE="

addons:
  coverity_scan:
    project:
      name: "prozum/midiogre"
      description: "Build submitted via Travis CI"
    notification_email: nimoov@prozum.dk
    build_command_prepend: "make clean"
    build_command:   "make -j 8"
    branch_pattern: coverity

notifications:
  email: false
