language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo sed -i "s/precise/trusty/g" /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get -qq --no-install-recommends install cmake pkg-config doxygen libgtk-3-dev libexpat1-dev
  - echo "DEBUG:"
  - pkg-config --libs --cflags gtk+-3.0
  - cmake --version
  - pkg-config --version

install:
  - mkdir build
  - cd build
  - cmake ../ -DMAIN=1

script:
  - make -j 10
  - make install
