language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install pkg-config libgtk-3-dev
  - pkg-config --version
  - cmake --version

install:
  - mkdir build
  - cd build
  - cmake ../ -DMAIN=1

script:
  - make -j 10
  - make install
