package(default_visibility = ["//visibility:public"])

cc_library(
    name = "list",
    srcs = ["list.c"],
    hdrs = ["list.h"],
    copts = ["-O"],
    include_prefix = "list",
#    visibility = ["//main:__pkg__"],
)
