option(MAIN "Build midiogre" 0)
option(DEBUG "Build in debug mode" 1)
option(DOC "Generate documentation with Doxygen" 1)
option(LOCALE "Build with localization support" 0)
option(SAMPLES "Build samples" 1)
option(SQL "Build SQL samples" 1)
option(GUI "Build GUI samples" 1)
