message("* Installing to : ${CMAKE_INSTALL_PREFIX}")
message("")

if( GUI )
    message("* Build GTK version : Yes")
else()
    message("* Build GTK verision : No (default)")
endif()

if( CLI )
    message("* Build CLI version : Yes")
else()
    message("* Build CLI version : No (default)")
endif()

if( MINGW )
    message("* Build with MinGW : Yes")
else()
    message("* Build with MinGW : No (default)")
endif()

if( DOC )
    message("* Generate documentaion : Yes ")
else()
    message("* Generate documentaion : No (default)")
endif()

if( TESTS )
	message("* Build tests : Yes ")
else()
	message("* Build tests : No (default)")
endif()
