message("* Installing to : ${CMAKE_INSTALL_PREFIX}")

if( MAIN )
    message("* Build Midiogre : Yes")
else()
    message("* Build Midiogre : No (default)")
endif()

if( DEBUG )
    message("* Build in debug mode : Yes (default)")
else()
    message("* Build in debug mode : No")
endif()

if( MINGW )
    message("* Build with MinGW : Yes")
else()
    message("* Build with MinGW : No (default)")
endif()

if( DOC )
    message("* Generate documentaion : Yes (default)")
else()
    message("* Generate documentaion : No ")
endif()

if( SAMPLES )
    message("* Build samples : Yes (default)")
else()
    message("* Build samples : No")
endif()
